rabbitmq:
  host: foo.bar.baz
  port: 9000
http:
  port: 1337
  shared_secret: "my-shared-secret"
duply:
  config_home: /etc/duply
  container_name: "my-backup"
  arch_dir: "/var/duply/cache"
  max_age: "2M"
  volsize: 100
  max_full_backups: 2
  max_full_backup_age: "1M"
  max_full_with_incrs: 1
  auth:
    swift_auth_url: https://identity.api.zetta.io/v3
    swift_auth_version: 3
    swift_region_name: "no-osl1"
    swift_username: "username"
    swift_password: "password"
    swift_project_name: "project"
    swift_user_domain_name: "domain"
    swift_project_domain_name: "domain"
  root: /backup/
  globbing:
    include:
      - moo
    exclude:
      - dev
      - mnt
      - sys
      - proc
      - run
      - cache
      - boot
      - media
  keys:
    master:
      id: 6ACEC832
      data: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v1

        mQENBFiqJK0BCADB9ixE1+RG3OfLOImA+1e9WTezroQFHBScg8byESBmyVhfa0bd
        meTE4JST7fSVup+E/Shh2QvgkicLVOAWR8fAqp/1updU9kOhBnqm1OLUwKJ3xQl9
        XGgjcrllQiGpLgLUs/GwYU6EA/qXC5VTgFeofZ3ljiCF6guQ8slPDk7R00yVOAvB
        bETSisNTOCT91bU4MJ51UXNlOTk/SAtcNR8sLPg247DfDYzCVeU3IFt89sC1i49n
        nDg6jOErZKMg7mYItWnHA7h1H/jgbJDPl0orhG4e4Y4Snv4vp1EByMqSrt4u29g2
        hMbPdJ5dq7gOdHANhd1jjPja88wRU8O/hx/7ABEBAAG0MUVpbmFyIEZvcnNlbHYg
        KER1cGx5IE1hc3RlciBLZXkpIDxlaW5hckB6ZXR0YS5pbz6JATgEEwECACIFAliq
        JK0CGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEPz4FrJqzsgyCsQH/RIV
        osIy8cTE5pr5nn6i7SdMbjgs9zzGR7uTXEMJtvFRhF7uwn08TR7kMsK0zCuvok1O
        b8/mb+dWlFb9EzHn/RP1CV/GJamxQl2a+EFfZwYXoULb6KDPyV2CrxK9Eo9qj4ZK
        HbmI9hjHJQGO49jV+DkSyedi+eHBfws+pboAiRspUs68CwMa40C/fQ1xmQWNNJAz
        LDYFPUPF+9wXHXg0TNnG2YpQ7QV3+mgZwt9rlgjLZzdQ8HHNTHUSbgBvKuva8GMn
        TUFooXexuZIylGQMWpO4THjS7tYPRLyynTI27LHHtyqxSvu8QcYRT7YADX82rrJV
        0MGVWJGdGoKhXI6zTgK5AQ0EWKokrQEIANUP+dhYaS4NRdHc0fkzHfdoSGz0bmYL
        1FazW0upPBvt1b9F/u4/R19Tk0Fo2NerliXC8h1V4HIAOmX8hFt8PIJO4KbJ1MZK
        4vGKzP3LR4cGQZOKF5zsgqTl5HbncDs4vfS3KL1RHoTZvsAUr77kN5Cl1TcGa155
        Ukgh95Eo+vy8aPIA+cjGuDaLUZnZtG0KfplCzEmXLE9s3k2CrAnRw3tgOO6fbZz5
        Bkq2qOOEn8TJdsBQgTPC6ZS2bnTQcC08Yr52ODFDTFpCg5vzPILrKTiMWxWzOGo4
        YYHe2BDt/8flvIIAWG4FMtSkOpJyp3e7s+bs3r7kAUH2FiqKMRPmDCEAEQEAAYkB
        HwQYAQIACQUCWKokrQIbDAAKCRD8+Bayas7IMmqkCACpWLW6KJ54HzeXPdice/rJ
        sdbopdicyYTPiUhwjxt10cev123sLlppzbgAyijn4W3u91thXGn1611Xn2kLyTdE
        sDaw8/7TDoCz+VgMIBkBZ6J4jla7nhx07MDR8lNo63+nK7vnMKuC04tu7sg6BABI
        lu3tRICTMTQYikf1WSugXAc6ZiKPklTLTuyYSkQDu2MNKk6cDs7CQpJb9YWmcdVb
        tqn1F0G2M7lDLU6u8htf8+CElvQ25JPl+THdKPPNnqL9HFXabXJ322BCgOkjNeB5
        7edgnBYfcyI2pvJs0XqSMFvfJ+SoYm3QykyOtayorskAxfX1H4Xcwm4LR8m/K5A6
        =Dg3R
        -----END PGP PUBLIC KEY BLOCK-----
    host:
      password: password
      id: XXXXX
      public: |
        public host key
      private: |
        private host key
